### ISSUE TITLE
Feature: A model box should appear after clicking checkout button

### ISSUE THREAD

**Issue by rsinghcodes** [ieiciet/Checkout-ShoppingCart#12]
After successful checkout, a modal box should appear with some message to make the user feel that the order has been placed successfully.

**Comment by rsinghcodes** [comment]
Please assign it to me, I would like to work on this feature.

Thanks!

**Comment by ieiciet** [comment]
Nice one @rsinghcodes , We have assigned this issue to you. Go ahead and create a PR for the same.

**Comment by rsinghcodes** [comment]
Thank you very much😊, I am working on it and will make a PR for it soon.
