### ISSUE TITLE
Remove unwanted text in the site 

### ISSUE THREAD

**Issue by anubhav201241** [ieiciet/Checkout-ShoppingCart#18]
There is an unwanted text written in the footer, I want to remove them 
and also want to contribute to the contribution.md fle 

![image](https://user-images.githubusercontent.com/72249059/136543003-f8f4acb1-b465-41c3-8881-b790feff2d42.png)

@ieiciet Please Assign this issue to me!!

**Comment by ieiciet** [comment]
Thanks for putting this up in the issues, but it was one of the stashing issue and it has been already resolved. You can create more issues, We''ll assign those to you for sure. Happy Hacktoberfest'21 !

**Comment by Anubhavdevv** [comment]
Hey, @ieiciet Can I work upon Contribution.md readme file?
