### ISSUE TITLE
made the following Updates

### ISSUE THREAD

**Issue by AaquibAli** [ieiciet/Checkout-ShoppingCart#7]
1. add hover effect in order summery
2. change checkout button to animated button 
3. removing extra content below the checkout button

**Comment by AaquibAli** [comment]
Hii mentors i would like to change these issue in your  checkout shopping cart. Can u assign me this issue with hactoberfest accepted tag

**Comment by ieiciet** [comment]
Go ahead and create more issues, we'll surely assign them to you. Good work @AaquibAli .
